<?php

/**
 * Mapper_Base_Domains
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $content
 * @property date $date_insert
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Mapper_Base_Domains extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('list');
        $this->hasColumn('id', 'integer', 11, array(
             'autoincrement' => true,
             'primary' => true,
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('content', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('date_insert', 'date', null, array(
             'type' => 'date',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}