<?php

/**
 * Mapper_PagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mapper_PagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mapper_PagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mapper_Pages');
    }
    
    public function findCarsByModelId ($lang)
    {
        $q = Doctrine_Query::create()
                ->select()
                ->from('Mapper_Pages mp')
                ->where('lang = ?',$lang)
                ;
        
        return $q->fetchArray();
    }
}