<?php

/**
 * Mapper_UserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mapper_UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mapper_UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mapper_User');
    }

    /**
	 * Return user entity with role
	 * @param int $id
	 * @return  Doctrine_Query
	 */
	public function getUser($id)
	{
		return Doctrine_Query::create()
			->select()
			->from('Mapper_User user')
			->addWhere('user.id = ?', array($id));
	}

    /**
     * Returns list of users
     * @return Doctrine_Query
     */
    public function getUsers()
    {
        return Doctrine_Query::create()
                ->select()
                ->from('Mapper_User u');
    }
}