<?php

/**
 * Mapper_UsersaveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mapper_UsersaveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mapper_UsersaveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mapper_Usersave');
    }
}