<?php echo $this->doctype() . PHP_EOL; ?>
<html lang="en">
	<head>
	<?php
//	$this->headLink()->appendStylesheet('/css/frontend/main.css');
        
	$this->headLink()->appendStylesheet('/css/frontend/style_sheet.css');
        $this->headLink()->appendStylesheet('/css/backend/style_sheet.css');
        $this->headLink()->appendStylesheet('/css/frontend/jquery-ui-1.8.19.custom.css');
	$this->headLink()->appendStylesheet('/css/backend/jquery-ui-1.8.19.custom.css');
        $this->headLink()->appendStylesheet('/css/frontend/old.css');
	$this->headScript()->prependFile("/js/jquery/jquery-ui-1.8.19.js");
	$this->headScript()->prependFile("/js/jquery/jquery-1.7.2.js");
        $this->headScript()->prependFile("/js/jquery/ajax.js");
	echo $this->headTitle('Sandwiches') . PHP_EOL .
		 $this->headMeta() . PHP_EOL .
		 $this->headLink() . PHP_EOL .
		 $this->headStyle() . PHP_EOL .
         $this->dojo() . PHP_EOL .
		 $this->headScript();
	?>

	</head>

	<body class="claro">
        <?php echo $this->flashMessenger();?>
		<div id="header">
			<div class="container">
				<div id="logo"><a href="/"></a></div>
			</div>
		</div>

		<div id="wrapper">
			<div id="container" class="container">
				<div id="main" class="span-18 colborder">
                                    
                                        
                                                <div class="head">
                                                    <div class="btn">
                                                        <div class="lang">
                                                            <a href=""><img src="/images/default/md.png" /></a>
                                                            <a href=""><img src="/images/default/ru.png" /></a>                                                
                                                        </div>
                                                        <div class="sbox"></div>
                                                    </div>
                                                    
                                                    <div class="menupanel">
                                                        <?php echo $this->navigation()->menu()->setUlClass('menu'); ?>
                                                    </div>
                                                </div>
                                            
                                            <div class="flash-messages"><?php echo $this->layout()->top; ?></div>
                                            <div class="content">
                                                <?php echo $this->layout()->content; ?>
                                            </div>
                                            
                                        
                                    
				</div>
				<div id="sidebox" class="span-5 last">
					<?php echo $this->layout()->left; ?>
				</div>
			</div>
		</div>

		<div class="clear"></div>
		<div id="footer"><?php echo $this->layout()->footer; ?></div>
	</body>
</html>