actAs: []
options:
<<<<<<< HEAD
  type: INNODB
=======
  type: MyISAM
>>>>>>> 1667b1a54c052db39d48744740030250325f3c98
  collate: utf8_general_ci
  charset: utf8

User:
  tableName: user_users
<<<<<<< HEAD
=======
  options:
    type: MyISAM
    collate: utf8_general_ci
    charset: utf8
>>>>>>> 1667b1a54c052db39d48744740030250325f3c98
  columns:
    id:
      primary: true
      autoincrement: true
      type: integer
    email: string(64)
    password: string(32)
    firstname: string(255)
    middle: string(255)
    lastname: string(255)
    sex: string(1)
    birth_date: date
    street: string(255)
    house_number: string(16)
    zipcode: string(64)
    city: string(64)
    active: boolean
    account_type:
      type: enum
      values:
        - CLIENT
        - PSYCHOLOGIST
        - ADMIN
      default: CLIENT
  indexes:
    unique_email:
      fields: [email]
      type: unique
    account_type:
<<<<<<< HEAD
      fields: [account_type]
=======
      fields: [account_type]

Domains:
  tableName: list
  options:
    type: MyISAM
    collate: utf8_general_ci
    charset: utf8
  columns: 
    id:
      autoincrement: true
      primary: true
      type: integer(11)
    content: string(128)
    date_insert: date

Usersave:
  tableName: user_saved
  options:
    type: MyISAM
    collate: utf8_general_ci
    charset: utf8
  columns:
    id:
      autoincrement: true
      type: integer(11)
      primary: true
    domain_name: string(128)
    date_saved: date
    
>>>>>>> 1667b1a54c052db39d48744740030250325f3c98
