actAs: 
  Timestampable:
    created:
      name: created_at
      type: timestamp
      format: Y-m-d H:i:s
    updated:
      name: updated_at
      type: timestamp
      format: Y-m-d H:i:s
options:
  type: MyISAM
  collate: utf8_general_ci
  charset: utf8
  
Pages:
  tableName: pages
  options:
    type: MyISAM
    collate: utf8_general_ci
    charset: utf8
  columns:
    id:
      primary: true
      autoincrement: true
      type: integer
    lang: string(32)
    page_type: string(128)
    page_content: text
    
    
      

User:
  tableName: user_users
  options:
    type: MyISAM
    collate: utf8_general_ci
    charset: utf8
  columns:
    id:
      primary: true
      autoincrement: true
      type: integer
    email: string(64)
    password: string(32)
    firstname: string(255)
    middle: string(255)
    lastname: string(255)
    sex: string(1)
    birth_date: date
    street: string(255)
    house_number: string(16)
    zipcode: string(64)
    city: string(64)
    active: boolean
    account_type:
      type: enum
      values:
        - CLIENT
        - USER
        - ADMIN
      default: CLIENT
  indexes:
    unique_email:
      fields: [email]
      type: unique
    account_type:
      fields: [account_type]

